@echo off
echo ===========================================
echo Starting Daily Crescent AI Analysis Routine
echo ===========================================

REM Change directory to the root of the project to ensure the .env file is found
cd /d "C:\Users\kevin\OneDrive\Documents\GitHub\Crescent_AI"

echo.
echo [1/2] Generating the daily analysis report...
python agent_analysis/analysis_agent.py
IF %ERRORLEVEL% NEQ 0 (
    echo Error generated by analysis_agent.py. Aborting.
    exit /b %ERRORLEVEL%
)

echo.
echo [2/2] Emailing the generated report...
python agent_analysis/email_report.py
IF %ERRORLEVEL% NEQ 0 (
    echo Error generated by email_report.py. Aborting.
    exit /b %ERRORLEVEL%
)

echo.
echo ===========================================
echo Analytics routine finished successfully!
echo ===========================================
exit /b 0
